### ISSUE TITLE
Adicionar objeto a JSON

### ISSUE THREAD

**Issue by miguel-botelho** [444Duarte/PraxisMesaeOrdenatorum#3]
Na minha branch existe por lá uma função no listener do adicionar que adiciona um praxista. já tem os campos todos descriminados e o praxista criado também. alguém sabe como é que se adiciona agora ao JSON?
Saudações Académicas,
Puto Kengas

**Comment by afonsocastro96** [comment]
Feito, testa só: https://github.com/444Duarte/PraxisMesaeOrdenatorum/pull/4
